"""empty message

Revision ID: b03dd20f0385
Revises: ffc3c0440459
Create Date: 2026-01-30 19:38:45.553251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b03dd20f0385'
down_revision = 'ffc3c0440459'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_characters',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'character_id')
    )
    op.create_table('favorite_locations',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'location_id')
    )
    op.drop_table('favorites_table')
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_constraint('location_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.create_unique_constraint('location_name_key', ['name'])

    op.create_table('favorites_table',
    sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name='favorites_table_character_id_fkey'),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name='favorites_table_location_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorites_table_user_id_fkey'),
    sa.PrimaryKeyConstraint('location_id', 'character_id', 'user_id', name='favorites_table_pkey')
    )
    op.drop_table('favorite_locations')
    op.drop_table('favorite_characters')
    # ### end Alembic commands ###
